# Site name
site_name: Course Outlines
site_description: "Various Course Outlines" 

# Navigation menu
nav:
  - Overview: index.md
  - IfATE:
    - DA4-M2: ifate/da4m2.md
    - DA4-M3: ifate/da4m3.md
    - DE5-M2: ifate/de5m2.md
  - Google:
    - GCPFCI:   google/gcpfci.md
    - GCPMDLDW: google/gcpmdldw.md
    - GCPAMIL:  google/gcpamil.md
  - Microsoft:
    - AI-900: microsoft/ai-900.md
    - DP-100: microsoft/dp-100.md
    - DP-203: microsoft/dp-203.md
    - DP-700: microsoft/dp-700.md
    - PL-300: microsoft/pl-300.md

# Theme
theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/table-of-contents
    static_templates:
      - 404.html

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
